import React from 'react';
import Navbar from './Navbar';
import Footer from './Footer';

const Guides = () => {
  return (
    <div className='h-screen gradient-bg-welcome '>
        <Navbar />
        <div className="w-full px-8 mt-[100px] gradient-bg-welcome">
            <h1 className='text-blue-400 sm:text-3xl text-5xl'>Crypto Wallet Guides</h1>
            <h4 className="text-slate-50 leading-8 text-xl ">Metamask Wallet</h4>
            
            <h6 className="text-left text-white mt-6">
            Welcome to this guide on securely setting up a MetaMask wallet. 
            This guide focuses on the security choices you can make when setting up your MetaMask wallet; 
            MetaMask is your entry point to the world of Ethereum - a
            blockchain platform designed for running apps and smart contracts.
            </h6>
            <div className="w-full my-6">
            <h4 className="text-white leading-8 text-xl mb-2">What is Metamask for Android ?</h4>
            <p className="text-gray-300">
             The MetaMask mobile app consists of two main parts: a wallet and a web browser. The wallet supports any token compatible with Ethereum, and the web browser
             is preconfigured for interacting with dapps and smart-contracts. MetaMask was first released in 2016, as a browser-extension, by ConsenSys - 
             the first company focused on building decentralized tools and infrastructure. Both MetaMask and ConsenSys have played monumental roles in bringing Ethereum to the mainstream. 
             It is hard to overstate the effect MetaMask has had on the Ethereum ecosystem. By making dapps and smart-contracts simple and intuitive to use, activity on the Ethereum 
             blockchain has enjoyed consistent growth.Metamask is an open-source wallet, active development happens on github. The wallet has tons of features, and is constantly 
             being updated and improved. MetaMask is available as a browser-extension for Chrome, Firefox, Brave, and Edge. In September of 2020, MetaMask released a mobile app for iOS and Android.
            </p>
            </div>

            <div className="w-full my-6">
            <h4 className="text-white leading-8 sm:text-xl text-2xl mb-2">How can you Download and install Metamask for Android?</h4>
            <p className="text-gray-300">
                From your mobile device, open the 'Play Store' and search for 
                'MetaMask' and click 'install'.
                Trust, but verify. When using any cryptocurrency wallet, it is important to make sure
                you are downloading the correct version. Check the store listing for the following info: 
                Version: 1.0.10 as of January 26, 2021 Offered by: MetaMask The `Version` number and the `Updated on` 
                date will change as the app is updated over time. The important part to verify is the `Offered by` field.
                Remember the phrase trust, but verify. Taking the extra step to verify can prevent loss of funds. 
                Trust, but verify is an important concept in having a security mindset.
            </p>
            </div>
            <div className="w-full my-6">
            <h4 className="text-white leading-8 sm:text-xl text-2xl mb-2">How can you create and set up MetaMask for Android?</h4>
            <p className="text-gray-300">
            MetaMask is a very easy wallet to get started with. No email address or personal identification is required. The process consists of two main steps - creating a password and backing
             up your seed phrase. You will be ready to explore the world of Ethereum in just a few minutes. MetaMask supports any token built on the Ethereum blockchain. You might come across 
             terms such as ERC-20 and ERC-721; these are just types of tokens. Safely backing up your MetaMask wallet is essential. This guide covers in detail how to securely back up your seed phrase in Section 5.
              Securely back up your seed phrase.MetaMask uses BIP39 to generate a seed phrase for your wallet. Your seed phrase will cover every token, address, and transaction generated by your wallet. 
              Think of it as your backup master key.When creating a new MetaMask Wallet, the default method is to create your wallet within the app. The more advanced method is to generate your own seed phrase directly. 
              We created detailed guides on how to create your own seed phrase.By following the appropriate directions, you can generate a seed phrase that is more secure than the default method used by wallets.
            </p>
            <p className='text-gray-300 mt-5 font-bold text-lg'>If you already have a seed phrase, proceed to Section 6. Initialize or import seed phrase.</p>
            
            <div className="flex flex-row justify-start items-center 
                 white-glassmorphism p-2 sm:mx-3 sm:my-3 mx-1 my-3 w-full cursor-pointer hover:shadow-xl">
                <div className="flex flex-1 flex-col ml-5">
                    <h1 className='text-white sm:text-xl text-2xl mt-2'>Create a New Wallet in MetaMask</h1>
                    <p className='text-white text-sm md: w-9/12 my-2'>In this section, you are going to create a new wallet in the MetaMask Android app using 
                        the wallet's default methods.To create a new wallet with a new seed phrase in MetaMask:
                    </p>
                    <ul className='text-gray-300 list-disc'>
                        <li>Open the MetaMask extension and tap on `Get Started`. This will bring you to the `Wallet Setup` screen</li>
                        <li>On the `Wallet Setup` screen you will be presented with 3 options:</li>
                        <li>Import using seed phrase</li>
                        <li>Sync with MetaMask extension</li>
                        <li>Create a new wallet</li>
                    </ul>

                    <p className='my-2 text-white font-bold sm:text-md text-lg'>The first step is to create your password and set up your login settings</p>
                    <ul className='text-gray-300 list-disc'>
                        <li>MetaMask cannot reset your password for you. Check the checkbox to confirm you understand this concept. If you want to reset your password, you will need your seed phase</li>
                        <li>Create your password using a combination of upper and lower case, numbers, and symbols. It's recommended to use a unique password that you have not used before.</li>
                        <li>Sign in with Biometrics? MetaMask supports biometric authentication if enabled on your device. Decide if you want to use biometric authentication with your MetaMask account by switching the toggle on/off.</li>
                        <li>When finished - tap on `Create password`</li>
                        <li>MetaMask will now create your wallet and bring you to the next screen in the setup process</li>
                    </ul>
                    
                </div>
                </div>
            </div>

            <div className="flex flex-row justify-start items-center 
                 white-glassmorphism p-2 sm:mx-3 sm:my-3 mx-1 my-3 w-full cursor-pointer hover:shadow-xl">
                <div className="flex flex-1 flex-col ml-5">
                    <h1 className='text-white sm:text-xl text-2xl mt-2'>Verify your seed phrase</h1>
                    <p className='text-white sm:text-md text-lg  md: w-9/12 my-2'>At this point, you will have a fully functioning cryptocurrency wallet that is able to store, send, and receive cryptocurrency. 
                        Before you put funds in your wallet, you need to create a backup and then verify your recovery phrase.
                    </p>
                    <ul className='text-gray-300 list-disc'>
                        <li>Secure Your Wallet - This is the most important step in creating your wallet.</li>
                        <li>MetaMask will give you two options on the `Secure Your Wallet` screen:</li>
                        <li>`Remind me later (Not recommended)`</li>
                        <li>`Start (Highly recommend)`← This is the one you want to select</li>
                        <li>MetaMask will display a warning before displaying your seed phrase:</li>
                        <li>Writing your seed phrase on paper comes with risks!</li>
                        <li>Tap on `Start` after you finish reading the warnings</li>
                    </ul>

                    <p className='my-2 text-white font-bold sm:text-md text-lg '>You are now ready to verify your seed phrase</p>
                    <ul className='text-gray-300 list-disc'>
                        <li>Tap on `View` for the seed phrase words to appear</li>
                        <li>Write down the 12 words in the correct order</li>
                        <li>Tap on `Continue`</li>
                        <li>Confirm your Seed Phrase</li>
                        <li>Your 12 words will appear on the screen out of order</li>
                        <li>Tap on each word in the correct order to verify your seed phrase</li>
                        <li>Tap `Complete Backup` when you are done</li>
                    </ul>
                </div>
            </div>

            <p className='text-gray-300 mt-5 font-bold'>MetaMask reminds you on the last screen that it can't recover your wallet so that
                you have to back up your seed phrase in a safe way, It's your responsibility and an ultra-important task! Leaving a hint where you saved your backup is a good idea, but be careful of revealing the location of backup 
                in a direct way, use something that no one can interpret, and of course, don't paste in your seed phrase.
            </p>

            <div className="flex flex-row justify-start items-center 
                 white-glassmorphism p-2 sm:mx-3 sm:my-3 mx-1 my-3 w-full cursor-pointer hover:shadow-xl">
                    <div className="flex flex-1 flex-col ml-5">
                     <p className='my-2 text-white font-bold sm:text-xl text-2xl'>Securely back up your seed phrase</p>
                     <p className="text-gray-300">
                        If you used Vault12 to generate your seed phrase, then congratulations! Your seed phrase is already securely backed up in your digital vault.
                        Your seed phrase is the master key to all of your cryptocurrency funds. MetaMask Wallet uses BIP39, which is the current industry best practice for generating seed phrases. The majority of modern wallets today use BIP39. This means your MetaMask 
                        seed phrase can be used to access your funds across many different wallets without knowing your MetaMask password.
                        Securely backing up your seed phrase is the most important step in creating a new wallet. To emphasize how important this is, consider how someone with your seed phrase could access your funds without you knowing.
                        Imagine a bad actor has your seed phrase, and you have your Metamask Wallet locked down with 2FA, IP address whitelisting, blocked tor access, and all the other security features. The attacker could simply open any wallet application, and import your seed phrase. The attacker now has access to all of your funds.
                        We want you to have a secure backup, so this never happens to you Nine out of ten wallet providers only mention one way to backup your seed phrase - by writing the seed phrase on paper. Wallet providers only mention this paper backup method because it is easy for beginners to do. Paper backups are simply not that secure.
                        We did extensive research and compiled the best ways to backup your seed phrase. We cover all the most well-known options, including next-generation options like how to back up your seed phrase in Vault12.
                        Once you have safely backed up your seed phrase, you can initialize your wallet using any BIP39 compatible wallet. In the next section, you will learn how you can initialize a MetaMask wallet using your seed phrase.
                     </p>
                    </div>
            </div>

            <div className="flex flex-row justify-start items-center 
                 white-glassmorphism p-2 sm:mx-3 mx-1 mt-3 w-full cursor-pointer hover:shadow-xl">
                <div className="flex flex-1 flex-col ml-5">
                    <h1 className='text-white sm:text-xl text-2xl mt-2'>Initialize or import seed phrase</h1>
                    <p className='my-2 text-white font-bold sm:text-md text-lg'>If you are following this guide from the beginning, and created your MetaMask Wallet the default 
                        way, using the app to `Create a Wallet`, then congratulations! Just be cautious about storing high amounts of funds with a wallet-generated seed phrase.
                        You are now ready to start using your MetaMask wallet.
                    </p>
                    <p className='text-white sm:text-sm text-md md: w-9/12 my-2'>In this section, you will learn how to initialize your wallet using a pre-generated seed phrase. 
                        There are 3 main reasons to generate your wallet using this method:
                    </p>
                    <ul className='text-gray-300 list-disc'>
                        <li>You lost access to your wallet, and you need to regain access to your wallet and your funds.</li>
                        <li>You want to access your wallet and funds using a different wallet app.</li>
                        <li>You want the best security, and you generated a seed phrase using an advanced method.</li>
                    </ul>

                    <p className='my-2 text-white font-bold sm:text-lg text-xl'>The Metamask Wallet makes the process super easy and user friendly. Let's get started.</p>
                    <ul className='text-gray-300 list-disc'>
                        <li>Open the MetaMask app and tap on `Get Started`. This will bring you to the `Wallet Setup` screen</li>
                        <li>On the `Wallet Setup` screen you will be presented with 3 options:</li>
                        <li>`Import using seed phrase`← This is the one you want to select</li>
                        <li>`Sync with MetaMask extension`</li>
                        <li>Type your seed phrase in the `Seed phrase` text box.</li>
                        <li>Any typos, misspellings, or typing the words in the incorrect order will invalidate the process and you will have to start over.</li>
                        <li>MetaMask supports using QR codes generated from a seed phrase. To use this feature, tap on the small QR code box in the bottom right 
                            corner of the Seed phrase text box.
                        </li>
                        <li>Create a strong password, e.g. using a combination of upper and lower case, numbers, and symbols. It's recommended to use a 
                            unique password that you have not used before.
                        </li>
                        <li>WARNING: MetaMask cannot reset your password for you. If you need to reset your password, you will need to recover your wallet
                             using a backup of your seed phrase. So be careful to remember your password.
                        </li>
                        <li>Confirm your password by typing it again</li>
                    </ul>
                    <p className='my-2 text-white font-bold sm:text-xl text-2xl'>Initialize Your Wallet</p>

                    <ul className="text-gray-300 list-disc">
                        <li>Look over your seed phrase to be sure there are no mistakes</li>
                        <li>If everything looks good, tap on `Import` to initialize your wallet</li>
                    </ul>
                </div>
            </div>
        </div>
        <p className="text-white px-[4%] pt-7 gradient-bg-welcome">CONGRATULATIONS! Your Metamask Wallet is Ready on Android</p>
        <Footer />
    </div>
  )
}

export default Guides